MQTT_BROKER = "adres"
MQTT_PORT = 1883

DEVICE_ID = "nr1"

MQTT_USERNAME = "esp32"
MQTT_PASSWORD = "haslo_mqtt"

MQTT_TOPIC_DATA = f"esp32/{DEVICE_ID}/data"
MQTT_TOPIC_CONFIG = f"esp32/{DEVICE_ID}/config"
MQTT_TOPIC_EVENT = f"esp32/{DEVICE_ID}/event"
MQTT_TOPIC_DEVICE_STATUS = f"esp32/{DEVICE_ID}/device_status"

FLASK_SECRET_KEY = "klucz"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD_HASH = "hash_hasla"