MQTT_BROKER = "192.168.1.100"
MQTT_PORT = 1883

DEVICE_ID = "nr1"

MQTT_TOPIC_DATA = f"esp32/{DEVICE_ID}/data"
MQTT_TOPIC_CONFIG = f"esp32/{DEVICE_ID}/config"
MQTT_TOPIC_ALARM = f"esp32/{DEVICE_ID}/alarm"
MQTT_TOPIC_STATUS = f"esp32/{DEVICE_ID}/status"