MQTT_BROKER = "192.168.1.1"
MQTT_PORT = 1883

DEVICE_ID = "nr1"

MQTT_TOPIC_DATA = f"esp32/{DEVICE_ID}/data"
MQTT_TOPIC_CONFIG = f"esp32/{DEVICE_ID}/config"
MQTT_TOPIC_EVENT = f"esp32/{DEVICE_ID}/event"
MQTT_TOPIC_DEVICE_STATUS = f"esp32/{DEVICE_ID}/device_status"

FLASK_SECRET_KEY = "abc123"
ADMIN_USERNAME = "abc123"
ADMIN_PASSWORD_HASH = "scrypt:abc123"